const char *fallbackShader_depthblur_vp =
"attribute vec4 attr_Position;\n"
"attribute vec4 attr_TexCoord0;\n"
"\n"
"uniform vec4   u_ViewInfo; // zfar / znear, zfar, 1/width, 1/height\n"
"\n"
"varying vec2   var_ScreenTex;\n"
"\n"
"void main()\n"
"{\n"
"	gl_Position = attr_Position;\n"
"	vec2 wh = vec2(1.0) / u_ViewInfo.zw - vec2(1.0);\n"
"	var_ScreenTex = (floor(attr_TexCoord0.xy * wh) + vec2(0.5)) * u_ViewInfo.zw;\n"
"\n"
"	//vec2 screenCoords = gl_Position.xy / gl_Position.w;\n"
"	//var_ScreenTex = screenCoords * 0.5 + 0.5;\n"
"}\n"
;
