const char *fallbackShader_shadowfill_fp =
"uniform vec4  u_LightOrigin;\n"
"uniform float u_LightRadius;\n"
"\n"
"varying vec3  var_Position;\n"
"\n"
"void main()\n"
"{\n"
"#if defined(USE_DEPTH)\n"
"	float depth = length(u_LightOrigin.xyz - var_Position) / u_LightRadius;\n"
" #if 0\n"
"	// 32 bit precision\n"
"	const vec4 bitSh = vec4( 256 * 256 * 256,   256 * 256,         256,           1);\n"
"	const vec4 bitMsk = vec4(              0, 1.0 / 256.0, 1.0 / 256.0, 1.0 / 256.0);\n"
"	\n"
"	vec4 comp;\n"
"	comp = depth * bitSh;\n"
"	comp.xyz = fract(comp.xyz);\n"
"	comp -= comp.xxyz * bitMsk;\n"
"	gl_FragColor = comp;\n"
" #endif\n"
"\n"
" #if 1\n"
"	// 24 bit precision\n"
"	const vec3 bitSh = vec3( 256 * 256,         256,           1);\n"
"	const vec3 bitMsk = vec3(        0, 1.0 / 256.0, 1.0 / 256.0);\n"
"	\n"
"	vec3 comp;\n"
"	comp = depth * bitSh;\n"
"	comp.xy = fract(comp.xy);\n"
"	comp -= comp.xxy * bitMsk;\n"
"	gl_FragColor = vec4(comp, 1.0);\n"
" #endif\n"
"\n"
" #if 0\n"
"	// 8 bit precision\n"
"	gl_FragColor = vec4(depth, depth, depth, 1);\n"
" #endif\n"
"#else\n"
"	gl_FragColor = vec4(0, 0, 0, 1);\n"
"#endif\n"
"}\n"
;
